apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
    version: v2
  name: reverseproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxy
        version: v2
    spec:
      containers:
      - image: hussain163/project3-reverseproxy
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always